import { useMemo, useState } from "react";
import { useAuth } from "@/_core/hooks/useAuth";
import { FreshnessBadge } from "@/components/FreshnessBadge";
import { PageFrame } from "@/components/PageFrame";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { directionLabels, downloadData, formatDate, toDateInput } from "@/lib/policy";
import { trpc } from "@/lib/trpc";
import { BookOpenCheck, Download, FileJson, Pencil, Plus, Search, Target, X } from "lucide-react";
import { toast } from "sonner";

type IndicatorForm = {
  name: string; policyArea: string; definition: string; calculation: string; unit: string; targetValue: string;
  targetDirection: "increase" | "decrease" | "maintain"; dataSourceId: string; lastUpdatedAt: string;
};
const emptyForm: IndicatorForm = { name: "", policyArea: "", definition: "", calculation: "", unit: "", targetValue: "", targetDirection: "increase", dataSourceId: "none", lastUpdatedAt: "" };

export default function Indicators() {
  const { user } = useAuth();
  const isAdmin = user?.role === "admin";
  const utils = trpc.useUtils();
  const [search, setSearch] = useState("");
  const queryInput = useMemo(() => search.trim() ? { search: search.trim() } : undefined, [search]);
  const indicatorsQuery = trpc.policy.indicators.list.useQuery(queryInput);
  const sourcesQuery = trpc.policy.sources.list.useQuery();
  const indicators = indicatorsQuery.data ?? [];
  const sources = sourcesQuery.data ?? [];
  const [dialogOpen, setDialogOpen] = useState(false);
  const [editingId, setEditingId] = useState<number | null>(null);
  const [form, setForm] = useState<IndicatorForm>(emptyForm);
  const createIndicator = trpc.policy.indicators.create.useMutation({ onSuccess: async () => { await utils.policy.indicators.list.invalidate(); setDialogOpen(false); toast.success("指標を登録しました。"); }, onError: error => toast.error(error.message) });
  const updateIndicator = trpc.policy.indicators.update.useMutation({ onSuccess: async () => { await utils.policy.indicators.list.invalidate(); setDialogOpen(false); toast.success("指標を更新しました。"); }, onError: error => toast.error(error.message) });
  const openCreate = () => { setEditingId(null); setForm(emptyForm); setDialogOpen(true); };
  const openEdit = (indicator: (typeof indicators)[number]) => { setEditingId(indicator.id); setForm({ name: indicator.name, policyArea: indicator.policyArea, definition: indicator.definition, calculation: indicator.calculation ?? "", unit: indicator.unit, targetValue: indicator.targetValue?.toString() ?? "", targetDirection: indicator.targetDirection, dataSourceId: indicator.dataSourceId?.toString() ?? "none", lastUpdatedAt: toDateInput(indicator.lastUpdatedAt) }); setDialogOpen(true); };
  const submit = (event: React.FormEvent) => { event.preventDefault(); const payload = { name: form.name, policyArea: form.policyArea, definition: form.definition, calculation: form.calculation || null, unit: form.unit, targetValue: form.targetValue === "" ? null : Number(form.targetValue), targetDirection: form.targetDirection, dataSourceId: form.dataSourceId === "none" ? null : Number(form.dataSourceId), lastUpdatedAt: form.lastUpdatedAt ? new Date(`${form.lastUpdatedAt}T00:00:00`) : null }; if (editingId) updateIndicator.mutate({ id: editingId, ...payload }); else createIndicator.mutate(payload); };
  const exportRows = indicators.map(indicator => ({ id: indicator.id, 指標名: indicator.name, 政策テーマ: indicator.policyArea, 定義: indicator.definition, 計算式: indicator.calculation ?? "", 単位: indicator.unit, 目標値: indicator.targetValue ?? "", 目標方向: directionLabels[indicator.targetDirection], データソース: indicator.dataSourceName ?? "", 最終更新日: formatDate(indicator.lastUpdatedAt) }));

  return (
    <PageFrame eyebrow="Indicator Dictionary / 03" title="指標辞書" description="KPIの意味、計算式、目標、データ来歴を共通化します。同じ名称でも定義が違えば比較できません。意思決定の前に、ここで根拠の前提を確認します。" actions={<div className="flex flex-wrap gap-2"><Button variant="outline" className="blueprint-secondary h-9 text-xs" disabled={!indicators.length} onClick={() => downloadData("policy-indicators", exportRows, "csv")}><Download className="mr-1.5 h-3.5 w-3.5" />CSV</Button><Button variant="outline" className="blueprint-secondary h-9 text-xs" disabled={!indicators.length} onClick={() => downloadData("policy-indicators", exportRows, "json")}><FileJson className="mr-1.5 h-3.5 w-3.5" />JSON</Button>{isAdmin ? <Button className="blueprint-primary h-9 text-xs" onClick={openCreate}><Plus className="mr-1.5 h-3.5 w-3.5" />指標を登録</Button> : null}</div>}>
      <section className="blueprint-panel p-5 md:p-6"><div className="relative z-10 flex flex-col gap-4 md:flex-row md:items-center md:justify-between"><div><p className="font-mono text-[10px] uppercase tracking-[0.16em] text-cyan-100/70">Metric specification</p><h2 className="mt-1 text-lg font-bold text-white">登録済みの政策指標</h2></div><div className="relative w-full md:w-80"><Search className="absolute left-3 top-1/2 h-3.5 w-3.5 -translate-y-1/2 text-cyan-100/55" /><Input className="blueprint-input h-9 pl-9 text-xs" value={search} onChange={event => setSearch(event.target.value)} placeholder="名称・テーマ・定義を検索" />{search ? <button className="absolute right-2 top-1/2 -translate-y-1/2 text-cyan-100/60" onClick={() => setSearch("")} aria-label="検索を消去"><X className="h-3.5 w-3.5" /></button> : null}</div></div>
        <div className="relative z-10 mt-5 grid gap-3 xl:grid-cols-2">{indicatorsQuery.isLoading ? <div className="border border-dashed border-cyan-100/25 p-10 text-center text-sm text-blue-100/60">指標辞書を読み込んでいます…</div> : indicators.length ? indicators.map(indicator => <article key={indicator.id} className="border border-cyan-100/20 bg-black/10 p-5"><div className="flex items-start justify-between gap-4"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><span className="status-pill text-cyan-100">{indicator.policyArea}</span><FreshnessBadge compact updatedAt={indicator.lastUpdatedAt} /></div><h3 className="mt-3 text-base font-bold text-white">{indicator.name}</h3></div>{isAdmin ? <Button variant="ghost" size="icon" className="-mr-2 -mt-2 h-8 w-8 text-cyan-100 hover:bg-white/10 hover:text-white" onClick={() => openEdit(indicator)} aria-label={`${indicator.name}を編集`}><Pencil className="h-3.5 w-3.5" /></Button> : null}</div><p className="mt-3 text-xs leading-5 text-blue-100/75">{indicator.definition}</p><dl className="mt-4 grid grid-cols-2 gap-x-5 gap-y-3 border-t border-white/10 pt-4 text-xs"><div><dt className="field-label">Target</dt><dd className="mt-1 text-white">{indicator.targetValue ?? "未設定"} {indicator.targetValue !== null ? indicator.unit : ""}</dd></div><div><dt className="field-label">Direction</dt><dd className="mt-1 text-white">{directionLabels[indicator.targetDirection]}</dd></div><div className="col-span-2"><dt className="field-label">Data source</dt><dd className="mt-1 text-cyan-100/80">{indicator.dataSourceName ?? "未紐付け"}</dd></div>{indicator.calculation ? <div className="col-span-2"><dt className="field-label">Calculation</dt><dd className="mt-1 whitespace-pre-wrap text-blue-100/70">{indicator.calculation}</dd></div> : null}</dl></article>) : <div className="col-span-full border border-dashed border-cyan-100/25 p-12 text-center"><BookOpenCheck className="mx-auto h-7 w-7 text-cyan-100/60" /><p className="mt-3 font-semibold text-cyan-50">登録済みの指標がありません</p><p className="mt-2 text-xs text-blue-100/60">管理者が定義とデータ来歴を登録すると、ダッシュボードで実測値を追跡できます。</p></div>}</div>
      </section>
      <Dialog open={dialogOpen} onOpenChange={setDialogOpen}><DialogContent className="max-h-[92vh] overflow-y-auto border-cyan-100/30 bg-[#082763] text-white sm:max-w-2xl"><DialogHeader><DialogTitle>{editingId ? "指標を編集" : "指標を登録"}</DialogTitle><DialogDescription className="text-blue-100/65">政策目的との関係、定義、比較可能性を明確にする項目を入力します。</DialogDescription></DialogHeader><form className="grid gap-4" onSubmit={submit}><div className="grid gap-4 md:grid-cols-2"><Field label="指標名"><Input className="blueprint-input" value={form.name} onChange={event => setForm({ ...form, name: event.target.value })} required /></Field><Field label="政策テーマ"><Input className="blueprint-input" value={form.policyArea} onChange={event => setForm({ ...form, policyArea: event.target.value })} required /></Field><Field label="単位"><Input className="blueprint-input" placeholder="人、%、件 など" value={form.unit} onChange={event => setForm({ ...form, unit: event.target.value })} required /></Field><Field label="目標値"><Input className="blueprint-input" type="number" step="any" value={form.targetValue} onChange={event => setForm({ ...form, targetValue: event.target.value })} /></Field><Field label="目標方向"><select className="blueprint-input h-10 w-full px-3 text-sm" value={form.targetDirection} onChange={event => setForm({ ...form, targetDirection: event.target.value as IndicatorForm["targetDirection"] })}>{Object.entries(directionLabels).map(([key, label]) => <option className="bg-[#082763]" key={key} value={key}>{label}</option>)}</select></Field><Field label="データソース"><select className="blueprint-input h-10 w-full px-3 text-sm" value={form.dataSourceId} onChange={event => setForm({ ...form, dataSourceId: event.target.value })}><option className="bg-[#082763]" value="none">未紐付け</option>{sources.map(source => <option className="bg-[#082763]" key={source.id} value={source.id}>{source.name}</option>)}</select></Field><Field label="最終更新日"><Input className="blueprint-input" type="date" value={form.lastUpdatedAt} onChange={event => setForm({ ...form, lastUpdatedAt: event.target.value })} /></Field></div><Field label="定義"><Textarea className="blueprint-input min-h-24" value={form.definition} onChange={event => setForm({ ...form, definition: event.target.value })} required placeholder="何を測る指標か、対象範囲と解釈上の留意点を含めて記載" /></Field><Field label="計算式"><Textarea className="blueprint-input min-h-20" value={form.calculation} onChange={event => setForm({ ...form, calculation: event.target.value })} placeholder="例：利用者数 ÷ 対象人口 × 100" /></Field><Button type="submit" className="blueprint-primary mt-1" disabled={createIndicator.isPending || updateIndicator.isPending}><Target className="mr-2 h-4 w-4" />{editingId ? "更新を保存" : "指標を登録"}</Button></form></DialogContent></Dialog>
    </PageFrame>
  );
}

function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="grid gap-2"><span className="field-label">{label}</span>{children}</label>; }
